# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d80cb145e6a99efac36c2050253a18be612b8188ac16481f6634461772cd80e1c0ee09243bb90168183041f55083d7748be3b451afb62d424e1906b1a5e3114e

test:
  secret_key_base: 6ee5ad800c4e38f97d96b17c658b1a88d1ed47335d76a148835ed0dda30eea6df8ebb20818f0d4069eefaf2df22f87e40d14e732c981d6f8cda9db82b4ce37e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
